<?php require 'layout.php'; userStart('Products','products'); ?>
<div class="container"><div class="page-head"><h1>Products</h1><p>Browse surgical and healthcare products.</p></div>
<div class="filter"><input id="productSearch" onkeyup="searchProducts()" placeholder="Search products..."><select><option>All Categories</option><option>Equipment</option><option>Protection</option><option>First Aid</option></select></div>
<div class="grid-4">
<div class="product-item"><div class="product-card"><button class="wishlist" onclick="addWishlist('p1')"><i class="bi bi-heart"></i></button><img src="/SurgicalStore/images/bp-monitor.jpg"><div class="product-info"><span class="category">Equipment</span><h3>BP Monitor</h3><span class="price">₹1,850</span><br><button class="btn primary small" onclick="addToCart('p1','BP Monitor',1850,'/SurgicalStore/images/bp-monitor.jpg')">Add to Cart</button></div></div></div>
<div class="product-item"><div class="product-card"><button class="wishlist" onclick="addWishlist('p2')"><i class="bi bi-heart"></i></button><img src="/SurgicalStore/images/pulse-oximeter.jpg"><div class="product-info"><span class="category">Equipment</span><h3>Pulse Oximeter</h3><span class="price">₹999</span><br><button class="btn primary small" onclick="addToCart('p2','Pulse Oximeter',999,'/SurgicalStore/images/pulse-oximeter.jpg')">Add to Cart</button></div></div></div>
<div class="product-item"><div class="product-card"><button class="wishlist" onclick="addWishlist('p3')"><i class="bi bi-heart"></i></button><img src="/SurgicalStore/images/first-aid-kit.jpg"><div class="product-info"><span class="category">First Aid</span><h3>First Aid Kit</h3><span class="price">₹650</span><br><button class="btn primary small" onclick="addToCart('p3','First Aid Kit',650,'/SurgicalStore/images/first-aid-kit.jpg')">Add to Cart</button></div></div></div>
<div class="product-item"><div class="product-card"><button class="wishlist" onclick="addWishlist('p4')"><i class="bi bi-heart"></i></button><img src="/SurgicalStore/images/digital-thermometer.jpg"><div class="product-info"><span class="category">Equipment</span><h3>Digital Thermometer</h3><span class="price">₹299</span><br><button class="btn primary small" onclick="addToCart('p4','Digital Thermometer',299,'/SurgicalStore/images/digital-thermometer.jpg')">Add to Cart</button></div></div></div>
<div class="product-item"><div class="product-card"><button class="wishlist" onclick="addWishlist('p5')"><i class="bi bi-heart"></i></button><img src="/SurgicalStore/images/face-mask.jpg"><div class="product-info"><span class="category">Protection</span><h3>Face Mask</h3><span class="price">₹120</span><br><button class="btn primary small" onclick="addToCart('p5','Face Mask',120,'/SurgicalStore/images/face-mask.jpg')">Add to Cart</button></div></div></div>
<div class="product-item"><div class="product-card"><button class="wishlist" onclick="addWishlist('p6')"><i class="bi bi-heart"></i></button><img src="/SurgicalStore/images/surgical-gloves.jpg"><div class="product-info"><span class="category">Protection</span><h3>Surgical Gloves</h3><span class="price">₹250</span><br><button class="btn primary small" onclick="addToCart('p6','Surgical Gloves',250,'/SurgicalStore/images/surgical-gloves.jpg')">Add to Cart</button></div></div></div>
</div></div>
<?php userEnd(); ?>